name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cqrs: ^6.0.0
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  contracts_generator:
    path: ..
