name: contracts_generator
repository: https://github.com/leancodepl/contractsgenerator-dart
description: Dart contracts client generator for a CQRS API.
version: 0.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  build: ^2.0.2
  build_resolvers: ^2.0.3
  build_runner_core: ^7.0.0
  build_test: ^2.1.0
  code_builder: ^4.0.0
  collection: ^1.15.0
  dart_style: ^2.0.1
  fixnum: ^1.0.0
  json_serializable: ">=4.0.0 <6.0.0"
  meta: ^1.3.0
  path: ^1.8.0
  protobuf: ^2.0.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  cqrs: ^6.1.0
  equatable: ^2.0.3
  lint: ^1.5.3
  test: ^1.17.10

executables:
  contracts_generator: contracts_generator
