name: leancode_contracts
repository: https://github.com/leancodepl/contractsgenerator-dart
description: Dart contracts runtime for a CQRS API.
version: 0.2.2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cqrs: ^6.2.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  leancode_lint: ^1.0.2
  test: ^1.17.10
