name: leancode_contracts
repository: https://github.com/leancodepl/contractsgenerator-dart
description: Dart contracts runtime for a CQRS API.
version: 0.7.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cqrs: ">=7.0.0 <10.0.0"
  equatable: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  leancode_lint: ^6.0.0
  test: ^1.17.10
