builders:
  contracts_serializable:
    import: "package:leancode_contracts_generator/builder.dart"
    builder_factories: ["contractsSerializable"]
    build_extensions: {".dart": [".contracts.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
