name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run lints
        run: dart analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: dart test

      - name: Dry run pub publish
        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
        run: dart pub publish --dry-run || true
