name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run lints
        run: dart analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: dart test

      - name: Dry run pub publish
        run: |
          # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
          dart pub publish --dry-run || true
