name: leancode_contracts_generator-publish

on:
  push:
    tags: ["leancode_contracts_generator-v*.*.*"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    defaults:
      run:
        working-directory: packages/leancode_contracts_generator

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8

      - name: Publish to pub.dev
        run: |
          dart pub publish -f
