name: leancode_contracts-test

on:
  push:
    branches: [main]
    paths:
      - packages/leancode_contracts/**
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - packages/leancode_contracts/**
      - .github/**

jobs:
  test:
    name: Dart ${{ matrix.dart_sdk }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dart_sdk: ["3.1.2"]

    defaults:
      run:
        working-directory: packages/leancode_contracts

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart_sdk }}

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none .

      - name: Run lints
        run: dart analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: dart test

      - name: Dry run pub publish
        run: |
          # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
          dart pub publish --dry-run || true
